env:
  global:
  - GO111MODULE=on

cache:
  cargo: true
  directories:
  - "$HOME/.cache/go-build"
  - "$GOPATH/pkg/mod"
  - build/centrifuge-chain

stages:
- Build
- Test & Lint

jobs:
  include:
  - stage: Build
    language: rust
    rust: nightly
    addons:
      apt:
        packages:
        - libcurl4-openssl-dev
        - libelf-dev
        - libdw-dev
        - cmake
        - gcc
        - binutils-dev
        - libiberty-dev
    name: Build centrifuge-chain
    script:
    - CMD=fetch ./scripts/centrifuge/ci.sh
    - CMD=build travis_wait 180 ./scripts/centrifuge/ci.sh
    deploy:
      provider: s3
      access_key_id: travis
      secret_access_key:
        secure: n23iVbMbbK+/hBj2x54Ce6xDIEnV2Y4Z3NZIiscQpvZasg5xgYmTpaMqlVIJJE2JLNUitM7IiOck9bUF556RO82/QUjkKiSkBjKEyFMES9z9K2YBo0HC3Ucdqyk8pGQPaYHTNbcLY1siJFEyVOnZ6RhXGWsPqKdxcfy65XSqom1I2USVzC21CQZ7zW8vtLy0spBpcIoc5Qr0UiGjuXAFCYzFVqcB/3UY1YNw7icpVHkI2bnjpG9zFlDcIFb64VNYDf0plwLECroMnipOkP4tAAucI2LR+THGnM694q11p4foTmbPTK2TmHZjgzRLpLfYeHwyfO+KhEt7YoHXI5SYxlNhgXoiPp8bYJexz75/6zVOAX5lRDEgknuU9ivdfVLToSJ6i1HLQRH4j7JmDjICWOLGnwz22H8nc7+vPzM07dh1OHcjujagK8Nt/aWbRp3xG+l30jpJY0qwvL4zb/+0HoWnsWTEXuDqn+RpVMEem4P7ZrPmChL86JMAOpkxoqTWdcfD5jSVRcks4tdT1+ewGmN+kgVn4P/wN05TQ01rFlXVOZT/QRsbQSNmF1B2ffdzFu5x7AhPoCVS0ad9RAvch6CiooB1ACNNj2Y4IvvKnqOtBYGtq7RSOMCo+iFGMMY24iwYfxouVlR3SCU3vWb478zLI3zpCdqkdYHJFzvTgD8=
      bucket: centchain
      local-dir: "./build/centrifuge-chain"
      acl: private

  - stage: "Test & Lint"
    language: go
    go: 1.13.x
    name: Golang-ci Linter
    script: make lint
  - stage: Test & Lint
    language: go
    go: 1.13.x
    name: Run Go tests
    script:
    - CMD=run ./scripts/centrifuge/ci.sh
    - SILENT=true make start_eth
    - make deploy_eth
    - make test
  - stage: Test & Lint
    language: node_js
    node_js: 12
    name: Run Truffle tests
    env: CI=true
    script:
    - cd on-chain/evm-contracts/
    - npm install
    - "./node_modules/.bin/truffle test"
