# Copyright 2020 ChainSafe Systems
# SPDX-License-Identifier: LGPL-3.0-only

env:
  global:
    - GO111MODULE=on

cache:
  cargo: true
  npm: true
  directories:
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod

install:
    - sudo add-apt-repository -y ppa:ethereum/ethereum
    - sudo apt-get update
    - sudo apt-get install ethereum
    - wget -P $HOME/bin/ https://storage.googleapis.com/centrifuge-dev-public/subkey  && chmod +x $HOME/bin/subkey

jobs:
  include:
    - language: go
      go: 1.13.x
      name: "Golang-ci Linter"
      script:
        - make clean # Avoid adding license to auto-gen files
        - make license-check
        - make setup-contracts
        - make lint

    - language: go
      go: 1.13.x
      name: "Run Go tests"
      script:
        - set -e
        - make clean && make setup-contracts
        - SILENT=true make start-eth
        - make deploy-eth
        - ./scripts/substrate/run_chain_ci.sh
        - make test