language: go

go:
  - 1.13.x

env:
  global:
    - GO111MODULE=on

cache:
  directories:
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod

matrix:
  include:
    - name: "Golang-ci Linter"
      script: make lint