# Copyright 2020 ChainSafe Systems
# SPDX-License-Identifier: LGPL-3.0-only

branches:
  only:
    - master

env:
  global:
    - GO111MODULE=on

cache:
  cargo: true
  npm: true
  directories:
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod

install:
    - sudo add-apt-repository -y ppa:ethereum/ethereum
    - sudo apt-get update
    - sudo apt-get install ethereum
    - wget -P $HOME/bin/ https://storage.googleapis.com/centrifuge-dev-public/subkey  && chmod +x $HOME/bin/subkey

jobs:
  include:
    - language: go
      go: 1.13.x
      name: "Golang-ci Linter"
      script:
        - make lint
        - rm -rf bindings/ # Avoid adding license to bindings
        - make license-check
    
    - language: go
      go: 1.13.x
      name: "Check solidity bindings"
      script:
        - set -e
        - make rebuild-contracts && make clean
        - go fmt ./...
        - git diff --exit-code ./bindings

    - language: go
      go: 1.13.x
      name: "Run Go tests"
      script:
        - set -e
        - npm install --global ganache-cli && SILENT=true ./scripts/start_ganache.sh
        - RUST_LOG=warn ./scripts/substrate/run_chain_ci.sh
        - make test

    - language: go
      go: 1.13.x
      name: "Run Go e2e tests"
      script:
        - set -e
        - npm install --global ganache-cli && SILENT=true ./scripts/start_ganache.sh
        - PORT=8546 SILENT=true ./scripts/start_ganache.sh
        - RUST_LOG=warn ./scripts/substrate/run_chain_ci.sh
        - make test-e2e