# Copyright 2020 ChainSafe Systems
# SPDX-License-Identifier: LGPL-3.0-only

branches:
  only:
    - master

env:
  global:
    - GO111MODULE=on

cache:
  cargo: true
  npm: true
  directories:
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod

install:
    - sudo add-apt-repository -y ppa:ethereum/ethereum
    - sudo apt-get update
    - sudo apt-get install ethereum
    - wget -P $HOME/bin/ https://storage.googleapis.com/centrifuge-dev-public/subkey  && chmod +x $HOME/bin/subkey


jobs:
  include:
    - stage: "Test"
      language: go
      go: 1.13.x
      name: "Golang-ci Linter"
      script:
        - make lint
        - rm -rf bindings/ # Avoid adding license to bindings
        - make license-check

    - stage: "Test"
      language: go
      go: 1.13.x
      name: "Run Go tests"
      script:
        - set -e
        - make clean && make rebuild-contracts
        - cd solidity && SILENT=true make start-ganache
        - cd .. && RUST_LOG=warn ./scripts/substrate/run_chain_ci.sh
        - make test

    - stage: "Test"
      language: go
      go: 1.13.x
      name: "Run e2e tests (Ganache)"
      script:
        - set -e
        - make clean && make rebuild-contracts
        - cd solidity && SILENT=true make start-ganache
        - SILENT=true PORT=8546 make start-ganache
        - cd .. && RUST_LOG=warn ./scripts/substrate/run_chain_ci.sh
        - make test-e2e

    - stage: "Test"
      language: go
      go: 1.13.x
      name: "Run e2e tests (Geth)"
      script:
        - set -e
        - make clean && make rebuild-contracts
        - QUIET=true FORK=true INSTANCE=1 ./scripts/geth/run_geth.sh
        - QUIET=true FORK=true INSTANCE=2 ./scripts/geth/run_geth.sh
        - RUST_LOG=warn ./scripts/substrate/run_chain_ci.sh
        - make test-e2e

    - stage: "Docker Deploy"
      if: (NOT type IN (pull_request)) AND (branch = master)
      script: ./scripts/ci_docker.sh
