# Copyright 2020 ChainSafe Systems
# SPDX-License-Identifier: LGPL-3.0-only

env:
  global:
    - GO111MODULE=on

cache:
  cargo: true
  directories:
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod

install:
    - sudo add-apt-repository -y ppa:ethereum/ethereum
    - sudo apt-get update
    - sudo apt-get install ethereum
    - wget -P $HOME/bin/ https://storage.googleapis.com/centrifuge-dev-public/subkey  && chmod +x $HOME/bin/subkey

jobs:
  include:
    - language: go
      go: 1.13.x
      name: "Golang-ci Linter"
      script:
        - make lint

    - language: go
      go: 1.13.x
      name: "Run Go tests"
      script:
        - SILENT=true make start_eth
        - make deploy_eth
        - make test

    - language: node_js
      node_js: 12
      name: "Run Truffle tests"
      env: CI=true
      script:
        - cd on-chain/evm-contracts/
        - npm install
        - ./node_modules/.bin/truffle test