# Copyright 2020 ChainSafe Systems
# SPDX-License-Identifier: LGPL-3.0-only

env:
  global:
    - GO111MODULE=on

cache:
  cargo: true
  directories:
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod
    - build/centrifuge-chain

stages:
  - "Build"
  - "Test & Lint"

jobs:
  include:
    - stage: "Build"
      language: rust
      rust: nightly
      addons:
        apt:
          packages:
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - cmake
            - gcc
            - binutils-dev
            - libiberty-dev
      name: "Build centrifuge-chain"
      script:
        - CMD=fetch ./scripts/centrifuge/ci.sh
        - CMD=build travis_wait 180 ./scripts/centrifuge/ci.sh

    - stage: "Test & Lint"
      language: go
      go: 1.13.x
      name: "Golang-ci Linter"
      script: make lint

    - stage: "Test & Lint"
      language: go
      go: 1.13.x
      name: "Run Go tests"
      script:
          - CMD=run ./scripts/centrifuge/ci.sh
          - SILENT=true make start_eth
          - make deploy_eth
          - make test

    - stage: "Test & Lint"
      language: node_js
      node_js: 12
      name: "Run Truffle tests"
      env: CI=true
      script:
        - cd on-chain/evm-contracts/
        - npm install
        - ./node_modules/.bin/truffle test