# Copyright 2020 ChainSafe Systems
# SPDX-License-Identifier: LGPL-3.0-only

env:
  global:
    - GO111MODULE=on

cache:
  cargo: true
  npm: true
  directories:
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod

install:
    - sudo add-apt-repository -y ppa:ethereum/ethereum
    - sudo apt-get update
    - sudo apt-get install ethereum
    - wget -P $HOME/bin/ https://chainbridge.ams3.digitaloceanspaces.com/subkey-v2.0.0 && mv $HOME/bin/subkey-v2.0.0 $HOME/bin/subkey && chmod +x $HOME/bin/subkey && subkey --version

jobs:
  include:
    - stage: "Test"
      language: go
      go: 1.15.x
      name: "Linter"
      script:
        - make lint
        - rm -rf bindings/ # Avoid adding license to bindings
        - make license-check

    - stage: "Test"
      language: go
      go: 1.15.x
      name: "Go tests"
      script:
        - set -e
        - docker-compose -f ./docker-compose-e2e.yml up -d
        - docker ps
        - travis_wait 30 make test

    - stage: "Test"
      language: go
      go: 1.15.x
      name: "E2E tests"
      script:
        - set -e
        - docker-compose -f ./docker-compose-e2e.yml up -d
        - docker ps
        - make test-e2e

    - stage: "Deploy"
      name: "Docker"
      script:
        - docker build -t chainsafe/chainbridge .
        - docker run chainsafe/chainbridge:latest --help
      deploy:
        - provider: script
          script: TARGET=default ./scripts/ci_docker.sh
          on:
            branch: master
        - provider: script
          script: TAG=$TRAVIS_TAG TARGET=release ./scripts/ci_docker.sh
          on:
            tags: true

    - stage: "Deploy"
      name: "Github Pages"
      script:
        - make build-mkdocs
      deploy:
        - provider: pages
          skip_cleanup: true
          github_token: $GITHUB_TOKEN
          local_dir: "./site"
          keep_history: true
          on:
            branch: master

