# Copyright 2020 ChainSafe Systems
# SPDX-License-Identifier: LGPL-3.0-only

branches:
  only:
    - master

env:
  global:
    - GO111MODULE=on

cache:
  cargo: true
  npm: true
  directories:
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod

install:
    - sudo add-apt-repository -y ppa:ethereum/ethereum
    - sudo apt-get update
    - sudo apt-get install ethereum
    - wget -P $HOME/bin/ https://storage.googleapis.com/centrifuge-dev-public/subkey  && chmod +x $HOME/bin/subkey


jobs:
  include:
    - stage: "Test"
      language: go
      go: 1.13.x
      name: "Linter"
      script:
        - make lint
        - rm -rf bindings/ # Avoid adding license to bindings
        - make license-check

    - stage: "Test"
      language: go
      go: 1.13.x
      name: "Go tests"
      script:
        - set -e
        - npm install --global ganache-cli
        - SILENT=true ./scripts/start_ganache.sh
        - RUST_LOG=warn ./scripts/substrate/run_chain_ci.sh
        - make test

    - stage: "Test"
      language: go
      go: 1.13.x
      name: "E2E tests"
      script:
        - set -e
        - docker-compose -f ./docker-compose-e2e.yml up -d
        - docker ps
        - make test-e2e

    - stage: "Docker Deploy (chainsafe/chainbridge)"
      if: (NOT type IN (pull_request)) AND (branch = master)
      script: ./scripts/ci_docker.sh
