env:
  global:
    - GO111MODULE=on

cache:
  directories:
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod

matrix:
  include:
    - language: go
      go: 1.13.x
      name: "Golang-ci Linter"
      script: make lint

    - language: go
      go: 1.13.x
      name: "Run Go tests"
      script:
          - SILENT=true make start_eth
          - make deploy_eth
          - make test

    - language: node_js
      node_js: 12
      name: "Run Truffle tests"
      env: CI=true
      script:
        - cd on-chain/evm-contracts/
        - npm install
        - ./node_modules/.bin/truffle test