# Copyright 2020 ChainSafe Systems
# SPDX-License-Identifier: LGPL-3.0-only

version: '3'
services:
  geth1:
    build:
      context:
        .
    environment:
      - KEYSTORE_PASSWORD=password
    command: --config /config/test.json --metrics --unsafe-rpc-external
    volumes:
      - ./:/config
      - ./keys:/keys/
    network_mode: host
    container_name: geth1
    ports:
    - "8545:8545"

  geth2:
    build:
      context:
        .
    environment:
      - KEYSTORE_PASSWORD=password
    command: --config /config/test.json --metrics --unsafe-rpc-external
    volumes:
      - ./:/config
      - ./keys:/keys/
    network_mode: host
    container_name: geth2
    ports:
    - "8546:8545"

  sub-chain:
    image: "chainsafe/chainbridge-substrate-chain:v1.0.0"
    container_name: sub-chain
    command: chainbridge-substrate-chain --dev --alice --ws-external --rpc-external
    ports:
    - "9944:9944"