---
# ------------------------------------------------------------------
# Cluster information
# ------------------------------------------------------------------
host: local
cluster: local
project: local
region: local

# ------------------------------------------------------------------
# Kubernetes Mapping info
# ------------------------------------------------------------------
service: cap-bridge-relayer
stage: local

# ------------------------------------------------------------------
# apps Info
# ------------------------------------------------------------------
apps:
  - name: cap-bridge-relayer
    path: ChainBridge
    replicas: 1
    ver: latest
    config: None
