name: Test and Lint

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    name: Lint and License Headers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.31
          args: --timeout=5m
      - name: License Check
        run: make license-check
