name: Node CI

on: [pull_request]

jobs:
  test:
    name: EVM Contract Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install, and test
      run: |
        cd on-chain/evm-contracts/
        npm install
        ./node_modules/.bin/truffle test
      env:
        CI: true
