steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
        with:
                node-version: '10.x'
    - run: cd contracts/evm-contracts/
    - run: npm install
    - run: ./node_modules/.bin/truffle test
